DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	original_url TEXT NOT NULL,
	clicks INTEGER NOT NULL DEFAULT 0,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'PENDING'
);

